### PR TITLE
Responsive CSS

### PR DESCRIPTION
**Pull request by ayushmansxn01**

### CODE REVIEW

**Review by xyrelljoi — APPROVED** [review]

**Comment by xyrelljoi** [comment]
uhm. @ayushmansxn01 i think there's a conflict in here

**Review by xyrelljoi — COMMENTED** [review]
Hi @ayushmansxn01! I reviewed the changes and it seems to be that this #3 is similar with your recent change in file `style.css` #2 . So I decided to not merge it.

`note: I was unable to merge it since there is a conflict. I followed the instruction below and it gave me an error, so I decided not merge it.`

Screenshots:
image
image

Thanks again @ayushmansxn01 ❤️

**Comment by ayushmansxn01** [comment]
Sorry for any inconvenience @xyrelljoi . Even I am new to the community and it was really my privilege working with you on your project .😊🤗

**Comment by ayushmansxn01** [comment]
And Thank "You" for making my contributions count ❤💕🎉🤗

**Pull request closed without merging**
